---
# Variables specific to `wordpress-deploy` test scenario.

project_type: wordpress
project_repo: "https://github.com/kentr/wordpress-test.git"

domain_name: "wordpress.test"
prod_domain: "{{ domain_name }}"
local_domain: "{{ domain_name }}"
vagrant_hostname: "{{ domain_name }}"

do_db_import: True
database_import_filename: "{{ playbook_dir }}/../{{ web_app_project_dir }}/resources/wordpress-test.sql.gz"

client_server_username: "wordpress"

wp_deploy: true

web_app_web_dir: "web"

# `wp_site_title` is defined so that the variable is available
# in the tests.
# If a database is imported, the value here must match whatever
# site title was used for the site from which the database
# was exported.
wp_site_title: 'WordPress Deploy Test'

instances:
  - name: "{{ local_domain }}"
    env: local
    uri: "http://{{ local_domain }}"
    type: "wordpress"
    root: "{{ web_app_web_root }}"

  - name: "{{ prod_domain }}"
    env: prod
    uri: "http://{{ prod_domain }}"
    type: "wordpress"
    root: "{{ web_app_web_root }}"

apache_redirect_missing_files: true

installed_extras: []

# Use sendmail, since we're not installing mailhog.
# See https://docs.drupalvm.com/en/latest/extras/mailhog/#disable-mailhog
php_sendmail_path: "/usr/sbin/sendmail -t -i"

# Currently required due to
# https://github.com/geerlingguy/ansible-role-mysql/issues/344
# Use path that's also available on the host, for prepare / cleanup.
ansible_python_interpreter: "python3"

# Firewall isn't necessary for CI, and it's breaking the build.
# Doesn't work to simply disable `ipv6`.
# See https://github.com/geerlingguy/ansible-role-firewall/blob/2.5.0/molecule/default/converge.yml#L8
firewall_enabled: false
