---
driver:
  name: docker
lint:
  name: yamllint
  enabled: false
platforms:
  # Platforms cannot be defined in `--base-config` file.
  # See https://github.com/ansible/molecule/issues/1328
  # MOLECULE_SCENARIO_NAME
  - name: "dvm-docker-${MOLECULE_SCENARIO_NAME}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ${MOLECULE_PROJECT_DIRECTORY}/:/var/www/drupalvm/:rw,delegated
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: wordpress-deploy
  create_sequence:
    - dependency
    - create
    - prepare
  converge_sequence:
    # - dependency
    # - create
    # - prepare
    - converge
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # Temporarily disable due to apache installation error.
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
