---

- name: Clone mysqludf_preg repo.
  git:
    depth: 1
    update: Yes
    repo: https://github.com/mysqludf/lib_mysqludf_preg.git
    dest: "{{ workspace }}/lib_mysqludf_preg"
    force: Yes
  when: project_type == "drupal"

- name: Ensure libmysqlclient-dev is installed.
  package:
    name: libmysqlclient-dev
    state: present
  when: project_type == "drupal"

# See http://stackoverflow.com/questions/3096989/libtool-version-mismatch-error
- name: Fix libtool version mismatch.
  command: autoreconf --force --install
  args:
    chdir: "{{ workspace }}/lib_mysqludf_preg"
  when: project_type == "drupal"

- name: Configure mysqludf_preg.
  command: ./configure
  args:
    chdir: "{{ workspace }}/lib_mysqludf_preg"
    creates: Makefile
  when: project_type == "drupal"

- name: Make install mysqludf_preg.
  command: make install
  args:
    chdir: "{{ workspace }}/lib_mysqludf_preg"
    creates: /usr/lib/mysql/plugin/lib_mysqludf_preg.so
  when: project_type == "drupal"

- name: Make installdb mysqludf_preg.
  command: make installdb
  args:
    chdir: "{{ workspace }}/lib_mysqludf_preg"
  when: project_type == "drupal"
