---

  # Copy database dump file to remote host and import it it to database 'drupal'
- name: Copy database dump file.
  copy:
    src: "{{ drupal_database_import_source }}"
    dest: /tmp
  when: database_import

- name: Import database.
  mysql_db:
    name: "{{ drupal_db_name }}"
    state: import
    target: "/tmp/{{ drupal_database_import_filename }}"
  when: database_import
