---
language: php
php: '7.1'
services: docker

env:
  global:
    - CONFIG: tests/config.yml
      MAKEFILE: example.drupal.make.yml
      COMPOSERFILE: example.drupal.composer.json
      HOSTNAME: drupalvm.test
      MACHINE_NAME: drupalvm
      IP: 192.168.88.88
      DRUPALVM_DIR: /var/www/drupalvm
      DRUSH_BIN: drush
      TEST_INSTALLED_EXTRAS: true
      CONTAINER_ID: dvm-test

  matrix:
    # Defaults - Ubuntu 16.04.
    - type: defaults
      distro: ubuntu1604
      local_config: "test/customized.config.yml"
      TEST_INSTALLED_EXTRAS: false

before_install:
  # Pull container.
  - docker pull geerlingguy/docker-${distro}-ansible:latest

  # Install lint tools.
  - gem install rubocop

script:
  # Vagrantfile syntax check.
  - 'rubocop ./Vagrantfile ./lib/drupalvm --except LineLength,Eval,MutableConstant,BlockLength,MethodLength,ConditionalAssignment,IndentArray,AlignParameters'

  # Run tests.
  - composer run-tests
