---
sudo: required
language: python
# Currently failing with Python3.
python: 2.7

cache: pip

services:
  - docker

branches:
  only:
  - travis-experiments
  - dev
  - customized

# Manual build matrix.
# See https://github.com/travis-ci/travis-ci/issues/1519
env:
  - MOLECULE_DISTRO=ubuntu1604 SCENARIO=default
  - MOLECULE_DISTRO=ubuntu1604 SCENARIO=wordpress-deploy
  - MOLECULE_DISTRO=ubuntu1604 SCENARIO=drupal-deploy-7

install:
  # `master` branch of `molecule` is required to get
  # `testinfra` >= `3.0` for support of Ansible `2.8`.
  # See https://github.com/philpep/testinfra/issues/431
  - pip install git+https://github.com/ansible/molecule.git docker

script:
  - "travis_wait 25 molecule -c molecule/base-config.yml test -s $SCENARIO"
