---
sudo: required
language: python
services:
  - docker

env:
  matrix:
    - MOLECULE_DISTRO: ubuntu1604

install:
  # Use `--pre` flag to get molecule >= 2.20.
  - pip install molecule docker --pre

script:
  - molecule test -s wordpress-deploy
