---
sudo: required
language: python
# Currently failing with Python3.
python: 2.7

cache: pip

services:
  - docker

branches:
  only:
  - dev
  - customized

# Manual build matrix.
# See https://github.com/travis-ci/travis-ci/issues/1519
env:
  - SCENARIO=default PYTHONWARNINGS='ignore::DeprecationWarning' MOLECULE_DISTRO=ubuntu1604
  - SCENARIO=wordpress-deploy PYTHONWARNINGS='ignore::DeprecationWarning' MOLECULE_DISTRO=ubuntu1604
  - SCENARIO=drupal-deploy-7 PYTHONWARNINGS='ignore::DeprecationWarning' MOLECULE_DISTRO=ubuntu1604

install:
  # `06133bf` is current HEAD for `molecule`.  Current official
  # pre-release versions don't have `testinfra` >= `3.0`, which is
  # required for support of Ansible `2.8`.
  # See https://github.com/philpep/testinfra/issues/431
  - pip install git+https://github.com/ansible/molecule.git@06133bf6253aaf3f4f5b7294cdbd9c5678e4fb8f docker

script:
  - "travis_wait 25 molecule -c molecule/base-config.yml test -s $SCENARIO"
