---
sudo: required
language: python
python: 3.7

cache: pip

services:
  - docker

branches:
  only:
  - dev
  - customized
  - fix-molecule

# Manual build matrix.
# See https://github.com/travis-ci/travis-ci/issues/1519
env:
  - SCENARIO=default PYTHONWARNINGS='ignore::DeprecationWarning' MOLECULE_DISTRO=ubuntu1804
  - SCENARIO=wordpress-deploy PYTHONWARNINGS='ignore::DeprecationWarning' MOLECULE_DISTRO=ubuntu1804
  - SCENARIO=drupal-deploy-7 PYTHONWARNINGS='ignore::DeprecationWarning' MOLECULE_DISTRO=ubuntu1804

before_install:
  - sudo apt-get -qq update

install:
  - python3 -m pip install molecule flake8 docker testinfra

script:
  - "travis_wait 25 molecule -c molecule/base-config.yml test -s $SCENARIO"
