---
vagrant_box: ubuntu/trusty64

vagrant_hostname: local.client.org
# For consistency with prod, you would set this to the same value as the user on
# the prod server.
vagrant_machine_name: client_server_username

# Primary directory that is synced onto the Vagrant machine.
# This should usually be equivalent to the directory on the host that contains
# the Drupal-VM code and your project.
# On production shared webservers, this is usually your user's home directory.

# On normal hosts, this would be something like this:
# "{{ ansible_user_home }}"
# Vagrant seems to choke if ansible_user_id isn't "vagrant", so we have to
# do a workaround:
base_synced_dir: "/home/{{ vagrant_machine_name }}"

# Root directory for the web app project.
# This is where the code and everything else in the project's repo will go.
# If you change this, you should also change the corresponding synced folder below.

# On normal hosts, this would be something like this:
# "{{ base_synced_dir }}/LOCAL_{{ ansible_user_id }}"
# Vagrant seems to choke if ansible_user_id isn't "vagrant", so we have to
# do a workaround:
web_app_project_root: "{{ base_synced_dir }}/LOCAL_{{ vagrant_machine_name }}"

# The location of the actual Drupal site code.
# It may be the same as web_app_project_root, depending on how your project is set up.
drupal_core_path: "{{ web_app_project_root }}/public_html"
drupal_file_private_path: ""

# Public / private files directories.  If your Drupal root directory is different from
# that on prod, then you'll want to set this to match your local site to override the
# values in the prod database.
# These should match what is in your Drush alias file, if you have set a value there.
drupal_file_public_path: 'sites/default/files'

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/extras/syncing-folders/ for more info.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  # If you change the `destination`, you probably also want to change `base_synced_dir`
  # above.
  - local_path: .
    destination: "{{ base_synced_dir }}"
    type: nfs
    create: true

# You probably don't want to change this.
drupal_composer_install_dir: "{{ web_app_project_root }}"

# Custom Drush alias tasks to insert just the local declaration into an existing
# alias file.
insert_local_drush_alias: true
# Prefix to use on the Drush alias file.  This value will determine the 1st part of
# the alias, between the "@" and the first ".".
# Example: if drush_alias_file_prefix = "my_project", the resulting aliases will be
#  - @my_project.loc
#  - @my_project.whatever
drush_alias_file_prefix: "{{ vagrant_machine_name }}"

# This is Drupal-VM's default Drush alias feature, which creates funky aliases and
# clobbers an existing file. So, it's disabled.
configure_drush_aliases: false

# Though site is not installed, this is used within the Pantheon project
# to form the database import file name.
# see drupal_database_import_filename
drupal_major_version: 7

# Install & configure basic site into database. Does not install code.
# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: false

# Set this to 'false' if you are using a different site deployment strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts' manually.
build_makefile: false

# Set 'build_makefile' to 'false' and this to 'true' if you are using a
# composer based site deployment strategy.
build_composer: false

# Set this to 'true' and 'build_makefile', 'build_composer' to 'false' if you
# are using Composer's create-project as a site deployment strategy.
build_composer_project: false

apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

# Configs for PHP 5.6 are in config.php5.6.yml
php_version: "5.6"

# Should be valid version at https://github.com/drush-ops/drush.
# This can be the the literal string HEAD, a branch name, a tag name.
# See http://docs.ansible.com/ansible/git_module.html#options.
# drush_version: "master"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  # - adminer
  # - blackfire
  # - cf_cli
  # - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  # - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - varnish
  - xdebug
  # - xhprof

################################################################################
# Core already installed in project directory
################################################################################

# Database import
#
# Source file for database.  Will be copied to the node and imported into
# the database specified for the Drupal site.
# Name of database import source file.
# drupal_database_import_filename: "dev.d{{ drupal_major_version }}.sql.gz"
# drupal_database_import_filename: "ukh20170117a.sql"
# Directory where the database source file resides.
# Path should be relative to the provisioning directory.
# drupal_database_import_directory: "../backup/dev/db"
#
# Add settings.local.php with database details.
# Will replace existing file.
custom_core_add_settings_local_php: True
#
# drupal_install_profile: "standard"
# drupal_file_private_path: "{{ drupal_core_path }}/sites/default/files/private"
# drupal_config_sync_directory: "{{ drupal_core_path }}/sites/default/config"

################################################################################



php_date_timezone: "America/Los_Angeles"

# install_wordpress: True
# wp_version: latest
# wp_domain: wp.loc
# wp_install_dir: "{{ web_app_project_root }}/wordpress_html"
# wp_db_name: "wordpress"
# wp_db_user: "wordpress"
# wp_db_password: "wordpress"
# wp_db_charset: "utf8mb4"
# wp_db_collate: "utf8mb4_general_ci"

# wp_table_prefix: "wp_"
# wp_debug: true
