---

- name: Download WordPress {{wp_version}} to {{ workspace }}.
  get_url:
    url: "http://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
    force: no
    dest: "{{ workspace }}/wordpress-{{ wp_version }}.tar.gz"

- name: Extract WordPress archive.
  unarchive:
    src: "{{ workspace }}/wordpress-{{ wp_version }}.tar.gz"
    dest: "{{ workspace }}"
    copy: no
    extra_opts: "--no-same-owner"

- name: Move extracted files to {{ wp_install_dir }}.
  synchronize:
    src: "{{ workspace }}/wordpress/"
    dest: "{{ wp_install_dir }}/"
    archive: True
  delegate_to: "{{ inventory_hostname }}"
