---

- name: Install site with `wp-cli`.
  become: no
  command: |
    wp \
    --path={{ wp_install_dir }} \
    --url={{ wp_domain }} \
    --admin_user={{ wp_admin_user }} \
    --admin_password={{ wp_admin_password }} \
    --admin_email={{ wp_admin_email }} \
    --title='{{ wp_site_title }}' \
    core install

- name: Update default plugins with `wp-cli`.
  become: no
  command: "wp --path={{ wp_install_dir }} plugin update --all"
