---
- name: Register information about the /vagrant directory.
  stat:
    path: /vagrant
  register: vagrant_directory

- name: Create or restore site database.
  include: mysql.yml
  when: wp_mysql_enable

- name: Ensure that installation directory exists.
  file:
    path: "{{wp_install_dir}}"
    state: directory

- name: Deploy WordPress if configured.
  include: tasks/deploy.yml
  when: wp_deploy

- name: Get information about index.php.
  stat:
    path: "{{ wp_install_dir }}/index.php"
  register: index_file

- name: Define wordpress_site_exists.
  set_fact:
    wordpress_site_exists: "{{ index_file.stat.exists|default(false) }}"

- name: Download WordPress if configured.
  include: tasks/download-wordpress.yml
  when: install_wordpress | default(False) and not wordpress_site_exists

- name: Fetch random salts for `wp-config.php`l
  command: curl https://api.wordpress.org/secret-key/1.1/salt/
  register: 'wp_salt'
  creates: "{{ wp_install_dir }}/wp-config.php"

- name: Copy `wp-config.php` file.
  template:
    src: wp-config.php.j2
    dest: "{{wp_install_dir}}/wp-config.php"

- name: Change ownership of installation directory.
  file:
    path: "{{wp_install_dir}}"
    owner: "{{ (vagrant_directory.stat.gr_name == 'vagrant_group') | ternary(omit, wp_core_owner) }}"
    group: "{{ (vagrant_directory.stat.gr_name == 'vagrant_group') | ternary(omit, wp_core_group) }}"
    state: directory
    recurse: yes

- name: Install WordPress site if configured.
  include: tasks/install-site.yml
  when: wp_install_site

- name: Install dummy data if configured.
  include: tasks/install-dummy-data.yml
  when: wp_install_dummy_data
