---
- name: Register information about the `wp_install_dir` directory.
  stat:
    path: "{{ wp_install_dir }}"
    get_checksum: no
  register: wp_install_dir_check

- name: Create or restore site database.
  include_tasks: mysql.yml
  when: wp_mysql_enable

- name: Deploy WordPress if configured.
  include_tasks: deploy.yml
  when: wp_deploy

- block:
    # If it's a link, check target.
    - name: "Get information on {{ wp_install_dir }}"
      stat:
        path: "{{ wp_install_dir_check.stat.lnk_source }}"
        get_checksum: no
      when: wp_install_dir_check.stat.exists and wp_install_dir_check.stat.islnk
      register: wp_install_dir_target_check
      failed_when: wp_install_dir_target_check is defined and not wp_install_dir_target_check.stat.isdir

    - name: Ensure that installation directory exists.
      file:
        path: "{{ wp_install_dir }}"
        state: directory
        owner: "{{ wp_core_owner }}"
        group: "{{ wp_core_group }}"
      when: not wp_install_dir_check.stat.exists

- name: Get information about index.php.
  stat:
    path: "{{ wp_install_dir }}/index.php"
  register: index_file

- name: Define `wordpress_site_exists`.
  set_fact:
    wordpress_site_exists: "{{ index_file.stat.exists|default(false) }}"

- name: Download WordPress if configured.
  include_tasks: download-wordpress.yml
  when: install_wordpress | default(False) and not wordpress_site_exists

- name: Check for existing `wp-config.php`.
  stat:
    path: "{{ wp_install_dir }}/wp-config.php"
    get_checksum: no
  register: wp_config_check

- name: Copy `wp-config.php` file.
  # `no_log` is set to hide database credentials, salts, etc.
  no_log: True
  template:
    dest: "{{ wp_install_dir }}/wp-config.php"
    mode: "ug=r,o="
    owner: "{{ wp_core_owner }}"
    group: "{{ wp_core_group }}"
    src: wp-config.php.j2
    force: no

- block:
    - name: Fetch random salts for `wp-config.php`.
      uri:
        url: https://api.wordpress.org/secret-key/1.1/salt/
        return_content: true
      register: wp_salt
      failed_when: wp_salt.status != 200

    - name: Add salts to `wp-config.php`.
      blockinfile:
        path: "{{ wp_install_dir }}/wp-config.php"
        block: "{{ wp_salt.content }}"
        insertbefore: '\/\*\*#@-\*\/'
  when: not wp_config_check.stat.exists

- name: Block access to `debug.log`.
  blockinfile:
    path: "{{ wp_install_dir }}/wp-content/.htaccess"
    create: yes
    mode: u=r,g=r,o=
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Block access to `debug.log`"
    block: |
      <Files "debug.log">
         deny from all
      </Files>
  when: wp_debug_log

- name: Block access to `wp-config.php`.
  blockinfile:
    path: "{{ wp_install_dir }}/wp-content/.htaccess"
    create: yes
    mode: u=r,g=r,o=
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Block access to `wp-config.php`"
    block: |
      <Files "wp-config.php">
         deny from all
      </Files>

- name: Install WordPress site if configured.
  include_tasks: install-site.yml
  when: wp_install_site

- name: Install dummy data if configured.
  include_tasks: install-dummy-data.yml
  when: wp_install_dummy_data
