---

- name: Create database for each site.
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_host: "{{ wp_db_host }}"
    login_user: "{{ wp_db_user }}"
    login_password: "{{ wp_db_password }}"
  when: wp_mysql_db_create

- name: Copy saved database to server.
  copy:
    src: "{{ wp_database_backup }}"
    dest: "{{ workspace }}/"
  when: wp_mysql_site_restore_saved_db

- name: Import saved database.
  block:

    # See https://github.com/ansible/ansible/issues/20196.
    - name: Create temporary MySQL options file.
      copy:
        content: |
          [client]
          user="{{ wp_db_user }}"
          password="{{ wp_db_password }}"
        dest: "{{ ansible_env.HOME }}/.ansible/tmp/.{{ wp_db_user }}.my.cnf"
        mode: "u=r,go="
      no_log: True

    - name: Import DB.
      mysql_db:
        name: "{{ wp_db_name }}"
        config_file: "{{ ansible_env.HOME }}/.ansible/tmp/.{{ wp_db_user }}.my.cnf"
        login_host: "{{ wp_db_host }}"
        login_user: "{{ wp_db_user }}"
        state: import
        target: "{{ workspace }}/{{ wp_database_backup | basename }}"
      register: wp_mysql_import_db_result

  always:
    - name: Remove temporary MySQL options file.
      file:
        path: "{{ ansible_env.HOME }}/.ansible/tmp/.{{ wp_db_user }}.my.cnf"
        state: absent

  become: no
  when: wp_mysql_site_restore_saved_db

- name: Create/assign database user to db and grant permissions.
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "'{{ wp_db_name }}.*:ALL'"
    state: present
  when: wp_mysql_db_create_users
