---
dependency:
  name: galaxy
  options:
    role-file: "provisioning/requirements.yml"
    ignore-errors: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
  playbooks:
    prepare: molecule/resources/prepare.yml
    # `cleanup` requires molecule >= 2.20.
    cleanup: molecule/resources/cleanup.yml
