---
dependency:
  name: galaxy
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
  playbooks:
    prepare: molecule/resources/prepare.yml
    # `cleanup` requires molecule >= 2.20.
    cleanup: molecule/resources/cleanup.yml
