---
# Tasks to perform WordPress code updates.

- name: WordPress plugin updates.
  block:
    - command: >
        wp
        --skip-plugins
        --skip-themes
        --skip-packages
        plugin update
        --all
        --format=json
      args:
        chdir: "{{ web_app_web_root }}"
      register: wp_plugin_update_results
  become: No

- name: WordPress theme updates.
  block:
    - command: >
        wp
        --skip-plugins
        --skip-themes
        --skip-packages
        theme update
        --all
        --format=json
      args:
        chdir: "{{ web_app_web_root }}"
      register: wp_theme_update_results
  become: No
