# Tasks to perform code updates.

- name: Create `updates` Git branch if necessary.
  command: "git checkout --no-track -b updates origin/master"
  args:
    chdir: "{{ web_app_project_root }}"

- include_tasks: "{{ playbook_dir }}/../scripts/misc/tasks/do-updates.{{ project_type }}.yml"
  when: project_type == 'drupal' or project_type == 'wordpress'
