---
# Tasks to perform WordPress code updates.

# git checkout -f HEAD -- public_html/wp-content/plugins; git clean -df -- public_html/wp-content/plugins

- name: WordPress plugin updates.
  block:
    - command: >
        wp
        --skip-plugins
        --skip-themes
        --skip-packages
        plugin update
        --all
        --format=json
      args:
        chdir: "{{ web_app_web_root }}"
      register: wp_plugin_update_results
