---
# Tasks to perform WordPress code updates.

- name: WordPress plugin updates.
  block:
    - command: >
        wp
        --skip-plugins
        --skip-themes
        --skip-packages
        plugin update
        --all
        --format=json
        --dry-run
      args:
        chdir: "{{ web_app_web_root }}"
      register: wp_plugin_update_results
