---

#- include_role:
#    name: drupalvm.hostname
#  when: hostname_configure

# Run firewall and security roles here to get them into place earlier.
#- include_role:
#    name: geerlingguy.firewall
#  when: firewall_enabled

- include_role:
    name: geerlingguy.security
  when: extra_security_enabled

- name: Set `lets_encrypt_domains`.
  set_fact:
    lets_encrypt_domains: >
      {{ lets_encrypt_domains | default([]) +
      [
        (item.servername | ipaddr) | ternary(item.serveralias, item.servername)
      ] }}
  with_items: "{{ apache_vhosts }}"

- name: Set `certbot_create_standalone_stop_services`.
  debug:
    msg: >
      {{ certbot_create_standalone_stop_services | default ([]) + [
        apache_service | default(Omit)
      ] }}

- name: Include certbot role.
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_certs: >
      {{ [
        {
          'domains': lets_encrypt_domains
        }
      ] }}
