---
# Installs BBC Wraith for visual regression testing.
# See https://github.com/BBC-News/wraith/

- name: Install imagemagick.
  become: Yes
  package:
    name: imagemagick
    state: present

# Nokogiri (wraith dependency) requires zlib.
# See https://github.com/flapjack/omnibus-flapjack/issues/72#issuecomment-73689368
- name: Install `zlib1g-dev`.
  become: Yes
  package:
    name: zlib1g-dev
    state: present
  when: ansible_os_family == 'Debian'

- name: Check gems path.
  command: ruby -rubygems -e 'puts Gem.user_dir'
  become: No
  register: gems_path_check
  when: gems_path is undefined

- name: Set gems path.
  set_fact:
    gems_path: "{{ gems_path_check.stdout }}"
  when: gems_path is undefined

# Add npm and gem executables to $PATH.
# See https://help.ubuntu.com/community/EnvironmentVariables
# In spite of `geerlingguy.ruby` adding the gems path to `/etc/profile.d`,
# it wasn't working correctly.
- name: Add gems path to `.profile`.
  blockinfile:
    path: ~/.profile
    backup: True
    insertafter: EOF
    content: "export PATH={{ npm_config_prefix }}/bin:{{ gems_path }}/bin:$PATH"

- name: Install configured gems.
  gem: "name={{ item }} state=present"
  with_items:
    - wraith
  register: wraith_install_result

- name: Get wraith gem directory for patch.
  command: "find {{ gems_path }} -name wraith-* -type d"
  register: wraith_gem_dir_check

- name: Set wraith gem directory for patch.
  set_fact:
    wraith_gem_dir: "{{ wraith_gem_dir_check.stdout }}"

- name: Apply wraith patches.
  patch:
    backup: yes
    basedir: "{{ wraith_gem_dir }}"
    strip: 1
    src: "{{ item }}"
  with_fileglob:
    - "{{ playbook_dir }}/../scripts/misc/patches/wraith/*.*"

- name: Add Wraith npm dependencies.
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    global: Yes
    state: latest
  become: Yes
  environment:
    NPM_CONFIG_PREFIX: "{{ npm_config_prefix }}"
    NODE_PATH: "$NODE_PATH:{{ npm_config_prefix }}/lib/node_modules"
    NPM_CONFIG_UNSAFE_PERM: "{{ npm_config_unsafe_perm }}"
  with_items:
    - name: phantomjs
    - name: casperjs
