---

- name: Ensure `workspace` directory exists.
  file:
    path: "{{ workspace }}"
    state: directory

- block:
    - name: Ensure `tzdata` package is installed.
      package:
        name: tzdata
        state: present

    - name: Set server timezone.
      timezone:
        name: "{{ php_date_timezone }}"

  when: php_date_timezone is defined

# `known_hosts` must come before any provisioning that uses SSH, such as Git checkouts.
- name: Check if local known_hosts file is present.
  stat: "path={{ known_hosts_path | default('~/.ssh/known_hosts') }}"
  register: known_hosts_file
  connection: local
  become: no

- name: Copy known_hosts file from host into Drupal VM.
  copy:
    src: "{{ known_hosts_path | default('~/.ssh/known_hosts') }}"
    dest: ~/.ssh/known_hosts
    mode: 0644
  become: no
  when: known_hosts_file.stat.exists

# Set up vagrant MySQL credentials.
# The criteria for this task are independent of the criteria for the setup in
# `geerlingguy.mysql`.  That role may also be configured to write a `.my.cnf` file
# for the vagrant user, in which case it will take precedence over this one.
- name: Copy user-my.cnf file with password credentials.
  template:
    src: "{{ playbook_dir }}/../scripts/misc/templates/user-my.cnf.j2"
    dest: "/home/{{ drupalvm_user }}/.my.cnf"
    owner: "{{ drupalvm_user }}"
    mode: 0600
