---
# Variables specific to default test scenario.

project_type: drupal

domain_name: "drupalvm.test"
prod_domain: "{{ domain_name }}"
local_domain: "{{ domain_name }}"
vagrant_hostname: "{{ domain_name }}"

client_server_username: "drupalvm"

drupal_major_version: 8
drupal_install_site: true
drupal_site_name: "Drupal Install Test"

web_app_web_dir: "web"

drupal_build_composer: true
drupal_build_composer_project: true

instances:
  - name: "{{ local_domain }}"
    env: local
    uri: "http://{{ local_domain }}"
    type: "drupal"
    root: "{{ web_app_web_root }}"
    drush_alias_file_prefix: "{{ cli_alias_file_prefix }}"
    repo: "{{ project_repo }}"
    ssh_host: "{{ local_domain }}"
    ssh_user: "{{ ansible_user|default('root') }}"
    drush_ssh_options: "-o PasswordAuthentication=no -i {{ lookup('env','HOME') }}/.vagrant.d/insecure_private_key -o LogLevel=quiet"
    drush_alias_is_local_on_remote_node: True

  - name: "{{ prod_domain }}"
    env: prod
    uri: "http://{{ prod_domain }}"
    type: "drupal"
    root: "{{ web_app_web_root }}"
    drush_alias_file_prefix: "{{ cli_alias_file_prefix }}"
    repo: "{{ project_repo }}"
    ssh_host: "{{ domain_name }}"
    ssh_user: "{{ client_server_username }}"

apache_redirect_missing_files: False

installed_extras:
  - drush

# Use sendmail, since we're not installing mailhog.
# See https://docs.drupalvm.com/en/latest/extras/mailhog/#disable-mailhog
php_sendmail_path: "/usr/sbin/sendmail -t -i"

# Install drush globally to prevent need for project-specific drush.
# Installing from source due to composer global installation as `root`.
drush_launcher_install: false
drush_composer_global_install: false
drush_install_from_source: true

# Currently required due to
# https://github.com/geerlingguy/ansible-role-mysql/issues/344
# Use path that's also available on the host, for prepare / cleanup.
ansible_python_interpreter: "python3"

# Firewall isn't necessary for CI, and it's breaking the build.
# Doesn't work to simply disable `ipv6`.
# See https://github.com/geerlingguy/ansible-role-firewall/blob/2.5.0/molecule/default/converge.yml#L8
firewall_enabled: false
