---
# This file contains role setup and test variables / overrides
# that are specific to the scenario (if any).
#
# General setup variables that apply to all scenarios should go
# in `molecule/resources/prepare-vars.yml`.

wp_deploy: true
wp_deploy_repo: "https://github.com/kentr/wordpress-test.git"

# To be consistent with `prepare-vars.yml`.
wp_deploy_dir: "/var/www/wordpress"

# The `web` directory is specific to the project's
# file structure, as cloned from the repo.
#
# The project should be cloned to `wp_deploy_dir`, and
# then the `web` directory is within that clone.
#
# Note: The following was not working in the python test file:
# `wp_install_dir: "{{ wp_deploy_dir }}/web"`:
wp_install_dir: "/var/www/wordpress/web"

wp_table_prefix: 'wp_table_prefix_test_'

# Run the WordPress installation.
wp_install_site: True
wp_site_title: 'WordPress Deploy Test'
wp_admin_email: "test@{{ wp_domain }}"

# Allow WP-CLI to run as root in this scenario.
# This is currently required by the Docker driver tests,
# which run as root.
wp_cli_allow_as_root: true
