---

# Install WP-CLI before attempting WordPress setup.
- name: Include `mychiara.wp-cli` role to setup WP-CLI.
  include_role:
    name: mychiara.wp-cli
  when: project_type == "wordpress" or "wp-cli" in installed_extras
  tags:
    - wordpress

# Call the existing `kentr.wordpress` role with pre-existing values
# for `wp_install` or `wp_deploy`.
- name: Include `kentr.wordpress` role to setup WordPress.
  include_role:
    name: kentr.wordpress
  when: project_type == "wordpress"
  tags:
    - wordpress

- name: Include `kentr.setup-wp-cli` role to setup WP-CLI.
  include_role:
    name: kentr.setup-wp-cli
  vars:
    installations: "{{ instances }}"
  when: (project_type == "wordpress" or "wp-cli" in installed_extras) and wp_setup_wp_cli | default(False)
  tags:
    - wordpress
