---

- name: Add Apache redirect for missing files (Drupal).
  set_fact:
    # Apache vhost extra parameters to force redirect to https version.
    apache_vhosts_extra_parameters_site: |
      {{ apache_vhosts_extra_parameters_site | default('') }}
      <IfModule mod_rewrite.c>
      RewriteEngine on
      # Attempt to load files from production if
      # they're not in our local version
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
      # Don't redirect for image styles.  Otherwise, derivatives won't be
      # generated on the fly.
      RewriteCond %{REQUEST_URI} !/{{ drupal_file_public_path }}/styles(.*?)/?.*
      RewriteRule ^/{{ drupal_file_public_path }}(.*) \
        {{ prod_uri }}/{{ drupal_file_public_path }}$1 [NC,L]
      </IfModule>
  when: apache_redirect_missing_files | default(False) and drupalvm_webserver == 'apache' and project_type == 'drupal'
  tags:
    - webserver

- name: Add Apache redirect for missing files (WordPress).
  set_fact:
    # Apache vhost extra parameters to force redirect to https version.
    apache_vhosts_extra_parameters_site: |
      {{ apache_vhosts_extra_parameters_site | default('') }}
      <IfModule mod_rewrite.c>
      RewriteEngine on
      # Attempt to load files from production if
      # they're not in our local version
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
      RewriteRule ^/wp-content/uploads(.*) \
        {{ prod_uri }}/wp-content/uploads$1 [NC,L]
      </IfModule>
  when: apache_redirect_missing_files | default(False) and drupalvm_webserver == 'apache' and project_type == 'wordpress'
  tags:
    - webserver

- name: Run Apache role after changing vhost extra parameters.
  include_role:
    name: geerlingguy.apache
  when: apache_redirect_missing_files | default(False) and drupalvm_webserver == 'apache'
  tags:
    - webserver

# RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
# RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
# RewriteRule ^/wp-content/uploads(.*) http://interview-wp.radicaldesigns.org/wp-content/uploads$1 [NC,L]
