---
# tasks file for kentr.setup-drush

- name: Ensure .bashrc exists.
  become: no
  file:
    path: "~/.bashrc"
    state: touch

- name: Run `drush init`.
  become: no
  command: drush init -y
  args:
    creates: ~/.drush/drush.bashrc
    chdir: "{{ drupal_core_path }}"

- name: Enable `structure-tables-key, common`.
  become: no
  lineinfile:
    backup: yes
    dest: ~/.drush/drushrc.php
    state: present
    regexp: "^(\\# )?\\$options\\[.structure-tables.\\]\\[.common.\\]"
    line: "$options['structure-tables']['common'] = array({{ drush_sync_structure_tables_common }});"
    create: Yes
  when: drush_enable_structure_tables_key_common | default(False)

- name: Enable dated `result-file` and `gzip` for `sql-dump.
  become: no
  blockinfile:
    backup: yes
    dest: ~/.drush/drushrc.php
    marker: "// {mark} ANSIBLE MANAGED BLOCK"
    state: present
    insertafter: EOF
    content: |
      $command_specific['sql-dump'] = array(
        'result-file' => '{{ drush_sql_dump_dir }}/@DATABASE_@DATE.sql',
        'gzip' => 1,
        'structure-tables-key' => 'common',
      );
    create: Yes
  when: drush_enable_dated_result_file | default(True)

- name: Define `drush_9_or_higher`.
  set_fact:
    drush_9_or_higher: "{{ drush_version | version_compare('9', '>=') }}"

- name: Ensure `sites` directory exists.
  become: No
  file:
    path: ~/.drush/sites
    state: directory
  when: drush_9_or_higher

- include_tasks: setup-one-site.yml
  with_items: "{{ installations }}"
