---
##########################################################################################
# Sets up remote Drush aliases for a site def.
#
# Expects parameter:
# item:
#   ssh_host: Required. Hostname that Drush should use for SSH (remote) operations.
#
#   ssh_user: Required. User that Drush should use for SSH (remote) operations.
#
#   drush_ssh_options: Required. Additional options that Drush should use for SSH (remote)
#       operations.
#
#   root: Optional. Absolute path to the item's root web folder.  No default.
#       If a Pantheon site is detected, this property will be ignored.
#       See https://github.com/drush-ops/drush/issues/313
#
#   env: Required. The environment for this installation.  Will be the ".xyz" suffix
#       for the alias.  Typical value would be one of [dev | stage | prod].
#
#   uri: Required. Full URI of site home page, including protocol (http / https).
#
#   site_directory: Optional. Directory under "sites/" that holds settings.php, etc.
#       Default is 'default'
#
#   drush_alias_file_prefix: Optional. Prefix for drush alias file. Determines the
#       prefix used in the site alias.  E.g., a value of "my-site" creates the aliases
#       "@my-site", "@my-site.*".
#       Defaults to the Ansible inventory_hostname.
#
#   drush_alias_include_on_remote_node: EXPERIMENTAL. Optional.  Default = True.  If True,
#       an alias definition for this item will be on the remote node.
#
#   drush_alias_is_local_on_remote_node: Optional.  If True, the alias
#       created for this item on the remote node will be configured as a "local" alias.
#       It will not have SSH connection information, and Drush will behave as though the
#       site is on the machine on which Drush is run.
#
#       Defaults:
#         - True the `env` property is in ['prod', 'stage'].
#         - False otherwise.
#
#       Note that for aliases created on `localhost`, this value is ignored and all aliases
#       are created as "remote" aliases
#
#   drush_structure_tables: Optional.  List of strings containing table names to be added
#       as `structure-tables` options.
#
#   drush_path_aliases: Optional.  Dictionary of path aliases.
#       Example:
#       ```
#       drush_path_aliases:
#         '%files': 'sites/default/files'
#         '%drush-script': 'drush'
#       ```
#
#   drush_db_url: Optional. String database URL in the format expected by the Drush
#       `--source-db-url` option.
#       Will be added to the alias block as a `db-url` property.
##########################################################################################

# ----------------------------------------------
# REMOTE

# TODO: Move one-time tasks to `main.yml`.

# Create wrapper php file for aliases if needed.
- name: Ensure remote Drush alias file exists.
  become: No
  template:
    # Don't overwrite existing file.
    force: No
    dest: "~/.drush/{{ item.drush_alias_file_prefix | default(inventory_hostname) }}.aliases.drushrc.php"
    src: templates/drush.aliases.drushrc.php.j2
  when: not drush_9_or_higher

- name: Define `drush_single_alias_template`.
  set_fact:
    drush_single_alias_template: "{{ drush_9_or_higher | ternary('single-alias-block.yml.j2', 'single-alias-block.j2') }}"

- name: Define remote Drush alias file, Drush < 9.
  set_fact:
    drush_remote_alias_file: "~/.drush/{{ item.drush_alias_file_prefix | default(inventory_hostname) }}.aliases.drushrc.php"
  when: not drush_9_or_higher

- name: Define remote Drush alias file, Drush >= 9.
  set_fact:
    drush_remote_alias_file: "~/.drush/sites/{{ item.drush_alias_file_prefix | default(inventory_hostname) }}.site.yml"
  when: drush_9_or_higher

- name: Insert remote Drush alias declarations.
  become: No
  blockinfile:
    dest: "{{ drush_remote_alias_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: @{{ item.drush_alias_file_prefix | default(inventory_hostname) }}.{{ item.env }}"
    state: present
    content:  "{{ lookup('template', 'templates/' + drush_single_alias_template) }}"
    # For Drush >= 9, it's a simple YAML file that can be created as we go.
    create: "{{ drush_9_or_higher }}"
  when: item.uri is defined and drush_aliases_remote | default(False)

# ----------------------------------------------
# LOCAL

- name: Set `drush_all_aliases_remote`.
  set_fact:
    drush_all_aliases_remote: True

# We're assuming that local Drush is >= 9.
- name: Define local Drush alias file.
  set_fact:
    drush_local_alias_file: "~/.drush/sites/{{ item.drush_alias_file_prefix | default(inventory_hostname) }}.site.yml"

- name: Insert local Drush alias declarations.
  delegate_to: 127.0.0.1
  become: No
  blockinfile:
    dest: "{{ drush_local_alias_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: @{{ item.drush_alias_file_prefix | default(inventory_hostname) }}.{{ item.env }}"
    state: present
    content:  "{{ lookup('template', 'templates/' + drush_single_alias_template) }}"
    # For Drush >= 9, it's a simple YAML file that can be created as we go.
    create: "{{ drush_9_or_higher }}"
  when: item.uri is defined and drush_aliases_local | default(False)
