---
- name: Set the PHP webserver daemon correctly when nginx is in use.
  set_fact:
    php_webserver_daemon: nginx
  when: drupalvm_webserver == 'nginx'
  tags: ['webserver', 'database', 'php']

- name: Set the correct XHProf package when PHP 5.6 is used.
  set_fact:
    xhprof_download_url: https://github.com/phacility/xhprof/archive/master.tar.gz
    xhprof_download_folder_name: xhprof-master
  when: php_version == '5.6'

# PHP version-specific directory may already be a link created by vagrant-cachier.
- name: Check if PHP version-specific workspace directory is already set up.
  stat:
    path: "/root/php{{ php_version }}"
  register: php_workspace_directory
  ignore_errors: true

- name: Ensure PHP version -specific workspace directory exists.
  file:
    path: "/root/php{{ php_version }}"
    state: directory
    mode: 0775
  tags: ['php']
  when: >
    not php_workspace_directory.stat.exists
    or (php_workspace_directory.stat.exists and not php_workspace_directory.stat.islnk)
