---

# EXPERIMENTAL Run Drupal / WordPress update process for projects
# within Drupal-VM environment.
#   - Performs code update.
#   - Calls kentr.drupal post-update tasks (Drupal-only).
#   - Installs Wraith (with dependencies).
#   - Sets up project-specific Wraith configuration.
#   - Runs Wraith smoke test on updated code.
#
# Prerequisites:
#   - VM is already set up to run Drupal.
#   - Drupal / WordPress code exists.
#   - The repo containing the Drupal code has a clean working directory
#     (no local modifications).
#   - There is no local branch named `updates`.
#   - Drupal-VM configuration files are present and correct.
#
# Usage:
#   `ansible-playbook provisioning/run-updates.yml`
#
# Extra Variables:
#   - drupal_update_security_only: Boolean. Default = False. If True, only
#     security updates will be applied.
#   - drupal_update_projects: Space-separated list of projects to update,
#     as for `drush pm-updatestatus`.  Default = '' (update all projects).
#
# TODO:
#   - Move playbook to `scripts` directory.
#   - Support non-composer Drupal projects.
#   - Move Wraith tasks to role.

- hosts: all
  become: No

  vars_files:
    - vars/main.yml
    - ../default.config.yml

  pre_tasks:
    - include: tasks/config.yml
      tags: ['always']

  roles:

  tasks:

  - include_tasks: "{{ playbook_dir }}/../scripts/misc/tasks/do-updates.yml"

  - include_tasks: "{{ playbook_dir }}/../scripts/misc/tasks/smoke-test.yml"
