---
- name: clear opcache
  command: >
    php -r
      "if (function_exists('apc_clear_cache')) {
        apc_clear_cache();
      }
      if (function_exists('opcache_reset')) {
        opcache_reset();
      }"
  args:
    chdir: "{{ wp_install_dir }}"
