---

- name: Init `.bashrc`.
  blockinfile:
    dest: ~/.bashrc
    marker: "# {mark} {{ bashrc_marker_text }}"
    state: present
    insertafter: EOF
    backup: yes
    create: yes
    content: "{{ lookup('template', 'templates/bashrc.j2') }}"
  when: init_bash_profile | default(True)

- name: Init `.bash_profile`.
  blockinfile:
    dest: ~/.bash_profile
    marker: "# {mark} {{ bash_profile_marker_text }}"
    state: present
    insertafter: EOF
    backup: yes
    create: yes
    content: "{{ lookup('template', 'templates/bash_profile.j2') }}"
  when: init_bash_profile | default(True)
